***EDA - Mitron bank***

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Cust = pd.read_csv('/content/sample_data/dim_customers.csv')
Spend = pd.read_csv('/content/sample_data/fact_spends.csv')

In [ ]:
Cust

,customer_id,age_group,city,occupation,gender,marital status,avg_income
0,ATQCUS1825,45+,Bengaluru,Salaried IT Employees,Male,Married,73523
1,ATQCUS0809,25-34,Hyderabad,Salaried Other Employees,Male,Married,39922
2,ATQCUS0663,25-34,Chennai,Salaried Other Employees,Male,Married,37702
3,ATQCUS0452,25-34,Delhi NCR,Government Employees,Male,Married,54090
4,ATQCUS3350,21-24,Bengaluru,Freelancers,Male,Single,28376
...,...,...,...,...,...,...,...
3995,ATQCUS3035,45+,Delhi NCR,Business Owners,Female,Married,72805
3996,ATQCUS2585,35-45,Mumbai,Salaried Other Employees,Female,Married,41343
3997,ATQCUS1229,35-45,Bengaluru,Salaried IT Employees,Male,Married,65948
3998,ATQCUS0581,25-34,Bengaluru,Government Employees,Male,Married,52589
3999,ATQCUS3477,25-34,Mumbai,Business Owners,Male,Single,73541

In [ ]:
Cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     4000 non-null   object
 1   age_group       4000 non-null   object
 2   city            4000 non-null   object
 3   occupation      4000 non-null   object
 4   gender          4000 non-null   object
 5   marital status  4000 non-null   object
 6   avg_income      4000 non-null   int64
dtypes: int64(1), object(6)
memory usage: 218.9+ KB

In [ ]:
Cust.describe(include= 'all')

,customer_id,age_group,city,occupation,gender,marital status,avg_income
count,4000,4000,4000,4000,4000,4000,4000.000000
unique,4000,4,5,5,2,2,NaN
top,ATQCUS1825,25-34,Mumbai,Salaried IT Employees,Male,Married,NaN
freq,1,1498,1078,1294,2597,3136,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,51657.032250
std,NaN,NaN,NaN,NaN,NaN,NaN,14690.140645
min,NaN,NaN,NaN,NaN,NaN,NaN,24816.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,38701.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,50422.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,64773.250000
max,NaN,NaN,NaN,NaN,NaN,NaN,86600.000000

In [ ]:
Cust.isnull().sum()

customer_id       0
age_group         0
city              0
occupation        0
gender            0
marital status    0
avg_income        0
dtype: int64

In [ ]:
Cust.duplicated().sum()

0

In [ ]:
Cust['age_group'].value_counts()

25-34    1498
35-45    1273
21-24     691
45+       538
Name: age_group, dtype: int64

In [ ]:
Cust['gender'].value_counts()

Male      2597
Female    1403
Name: gender, dtype: int64

In [ ]:
Cust['marital status'].value_counts()

Married    3136
Single      864
Name: marital status, dtype: int64

In [ ]:
Spend.isnull().sum()

customer_id     0
month           1
category        1
payment_type    1
spend           1
dtype: int64

In [ ]:
Spend.shape

(224692, 5)

In [ ]:
Spend.dropna(inplace= True)
Spend.shape

(224691, 5)

In [ ]:
Spend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 224691 entries, 0 to 224690
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   customer_id   224691 non-null  object
 1   month         224691 non-null  object
 2   category      224691 non-null  object
 3   payment_type  224691 non-null  object
 4   spend         224691 non-null  float64
dtypes: float64(1), object(4)
memory usage: 10.3+ MB

In [ ]:
Spend.duplicated().sum()

0

In [ ]:
Spend.describe(include= 'all')

       customer_id   month category payment_type          spend
count       224691  224691   224691       224691  224691.000000
unique        4000       6        9            4            NaN
top     ATQCUS0734  August  Apparel   Debit Card            NaN
freq            80   37751    25163        56363            NaN
mean           NaN     NaN      NaN          NaN     615.014696
std            NaN     NaN      NaN          NaN     659.962246
min            NaN     NaN      NaN          NaN       8.000000
25%            NaN     NaN      NaN          NaN     192.000000
50%            NaN     NaN      NaN          NaN     396.000000
75%            NaN     NaN      NaN          NaN     795.000000
max            NaN     NaN      NaN          NaN   10313.000000

In [ ]:
Spend.to_csv('fact_spend_clean.csv')

In [ ]:
Spend_cred = Spend[Spend['payment_type'] == 'Credit Card'].reset_index()
Spend_cred

        index customer_id    month           category payment_type   spend
0           0  ATQCUS1371     July  Health & Wellness  Credit Card  1114.0
1           1  ATQCUS0368  October          Groceries  Credit Card  1466.0
2           2  ATQCUS0595      May  Health & Wellness  Credit Card   387.0
3           3  ATQCUS0667  October        Electronics  Credit Card  1137.0
4           6  ATQCUS2843     June      Entertainment  Credit Card   268.0
...       ...         ...      ...                ...          ...     ...
56079  224650  ATQCUS1733     June      Entertainment  Credit Card   408.0
56080  224662  ATQCUS2627     June      Entertainment  Credit Card   266.0
56081  224669  ATQCUS1899  October               Food  Credit Card   301.0
56082  224683  ATQCUS1360   August               Food  Credit Card   774.0
56083  224690  ATQCUS1287  October              Bills  Credit Card  2113.0

[56084 rows x 6 columns]

In [ ]:
Spend_cred.to_csv('fact_spend_cred.csv')